---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  env-wp-config-extra: |
    {{ .Values.wordpress.config_extra | nindent 4 }}
  php-fpm-zz-docker.conf: |-
    [global]
    daemonize = no

    [www]
    listen = 9000
    listen.allowed_clients = ::1,127.0.0.1,10.42.0.1
    pm.status_path = "/status"
    pm.max_children = 75
    pm.process_idle_timeout = "10s"
    pm.max_requests =  500
    pm.start_servers = 5
    pm.min_spare_servers = 5
    pm.max_spare_servers = 75
    php_admin_value[memory_limit] = "2048M"

  php-opcache-recommended.ini: |-
    opcache.enable=1
    opcache.memory_consumption=128
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.validate_timestamps=0
    opcache.revalidate_freq=0
    opcache.fast_shutdown=1
    opcache.jit_buffer_size=500000000
    opcache.jit=1235

  zz-custom.ini: |-
    memory_limit = 2048M
    max_file_uploads = 50
    upload_max_filesize = 110M
    post_max_size = 120M
    max_execution_time = 300
    max_input_time = 600
    error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
    error_log = /dev/stderr
    log_errors = 1

  nginx.conf: |-
    worker_processes            auto;
    load_module modules/ngx_http_geoip2_module.so;

    error_log                   /dev/stderr;
    pid                         /tmp/nginx.pid;
    worker_rlimit_nofile        8192;

    events {
      worker_connections        8000;
      multi_accept              on;
    }

    http {
      geoip2 /usr/share/geoip/GeoLite2-Country.mmdb {
        $geoip2_data_country_code default=SE source=$http_x_forwarded_for country iso_code;
      }
      proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=STATIC:10m inactive=7d use_temp_path=off;
      # cache informations about FDs, frequently accessed files
      # can boost performance, but you need to test those values
      #open_file_cache           max=40000 inactive=20s;
      #open_file_cache_valid     60s;
      #open_file_cache_min_uses  2;
      #open_file_cache_errors    on;

      # copies data between one FD and other from within the kernel
      # faster than read() + write()
      sendfile                  on;

      # send headers in one piece, it is better than sending them one by one
      tcp_nopush                on;

      # don't buffer data sent, good for small data bursts in real time
      tcp_nodelay on;

      # gzip settings
      gzip                      on;
      gzip_buffers              16 8k;
      gzip_min_length           10k;
      gzip_proxied              any;
      gzip_types
          text/css
          text/javascript
          text/xml
          text/plain
          text/x-component
          application/javascript
          application/x-javascript
          application/json
          application/xml
          application/rss+xml
          application/atom+xml
          font/truetype
          font/opentype
          application/vnd.ms-fontobject
          image/svg+xml;

      # allow the server to close connection on non responding client, this will free up memory
      reset_timedout_connection off;

      # request timed out -- default 60
      client_body_timeout       60;

      # if client stop responding, free up memory -- default 60
      send_timeout              60;

      # server will close connection after this time -- default 75
      keepalive_timeout         75;

      # number of requests client can make over keep-alive
      keepalive_requests        1000;

      # other settings
      client_max_body_size      110M;
      client_body_buffer_size   10K;
      client_header_buffer_size 1k;
      large_client_header_buffers 2 1k;

      server_tokens             off;

      include                   mime.types;
      default_type              application/octet-stream;
      add_header                X-Frame-Options SAMEORIGIN;

      # trust these ips to set the correct http_x_forwarded_for header
      set_real_ip_from          10.0.0.0/8;
      set_real_ip_from          127.0.0.1;
      real_ip_header            X-Forwarded-For;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      log_format  main_geo  '$remote_addr - $remote_user [$time_local] "$request" '
                            '$status $body_bytes_sent "$http_referer" '
                            '"$http_user_agent" "$http_x_forwarded_for" '
                            '$geoip2_data_country_code';
      access_log                "/dev/stdout" main_geo buffer=2048 flush=5s;

      client_body_temp_path     /tmp/client_temp 1 2;
      proxy_temp_path           /tmp/proxy_temp_path 1 2;
      fastcgi_temp_path         /tmp/fastcgi_temp 1 2;
      uwsgi_temp_path           /tmp/uwsgi_temp 1 2;
      scgi_temp_path            /tmp/scgi_temp 1 2;

      server {
          listen [::]:8080 default_server;
          listen 8080 default_server;

          server_name _;
          root /var/www/html/web;
          index index.php;

          gzip on;
          gzip_proxied any;
          gzip_comp_level 4;
          gzip_types text/css application/javascript image/svg+xml;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;

          set $wordpress_auth "";
          set $proxy_cache_bypass 0;
          set $proxy_no_cache 0;
          set $requestmethod GET;
          if ($http_cookie ~* "wordpress_[a-f0-9]+|wp-postpass|wordpress_logged_in") {
              set $wordpress_auth wordpress_logged_in_$1;
              set $proxy_cache_bypass 1;
              set $proxy_no_cache 1;
              set $requestmethod $request_method;
          }
          if ($request_uri ~* "(/wp-admin/|/xmlrpc.php|/wp-(app|cron|login|register|mail).php|wp-.*.php|index.php|wp-comments-popup.php|wp-links-opml.php|wp-locations.php)") {
            set $fastcgi_cache_disabled 1;
          }

          # Don't use the cache for logged in users
          if ($http_cookie ~* "wordpress_[a-f0-9]+|wp-postpass|wordpress_logged_in") {
            set $fastcgi_cache_disabled 1;
          }
          # POST requests should always go to PHP
          if ($request_method = POST) {
            set $fastcgi_cache_disabled 1;
          }
          location ~* ^/wp/(wp-includes|wp-admin|wp-content)/.*\.(css|js)$ {
              root /var/www/html/web;

              # First try to locate the file as-is or fallback to removing the hash
              try_files $uri @strip_hash;

              expires max;
              log_not_found off;
              access_log off;
          }

          rewrite ^/(wp-.*.php)$ /wp/$1 last;
          rewrite ^/(wp-(content|admin|includes).*) /wp/$1 last;

          # Deny access to any files with a .php extension in the uploads directory
          # Works in sub-directory installs and also in multisite network
          location ~* /(?:uploads|files)/.*\.php$ {
            deny all;
          }
          location ~* /xmlrpc.php$ {
            deny all;
            access_log off;
            log_not_found off;
          }
          location ~* /app/.*.php$ {
            deny all;
            access_log off;
            log_not_found off;
          }
          location ~* /wp-includes/.*.php$ {
            deny all;
            access_log off;
            log_not_found off;
          }
          location ~* /wp-content/.*.php$ {
                  deny all;
                  access_log off;
                  log_not_found off;
          }
          location ~* /wp-admin/includes/.*.php$ {
            deny all;
            access_log off;
            log_not_found off;
          }

          location = /arto/api/event {
              proxy_pass https://plausible.io/api/event;
              proxy_buffering on;
              proxy_http_version 1.1;

              proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
              proxy_set_header X-Forwarded-Host  $host;
          }

          location ~* ^/app/(plugins|themes)/.*\.(css|js)$ {
              root /var/www/html/web;

              # First try to locate the file as-is or fallback to removing the hash
              try_files $uri @strip_hash;

              expires max;
              log_not_found off;
              access_log off;
          }

          # Fallback: Remove hash and look for non-hashed file
          location @strip_hash {
              # Rewrite to remove hash (e.g., .MS4w) and retry original path
              rewrite "^(/.+)\.[A-Za-z0-9]+(\.css|\.js)$" "$1$2" last;

              # Retry with a stripped hash or return 404 if the rewritten file could not be found
              try_files $uri =404;
          }

          # General WordPress routing: Core rewrite rules
          location / {

              try_files $uri $uri/ /index.php?$args;
          }

          # PHP handling for WordPress
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;

              if (!-f $document_root$fastcgi_script_name) {
                  return 404;
              }

              include fastcgi_params;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param PATH_INFO $fastcgi_path_info;

              fastcgi_pass 127.0.0.1:9000;
              fastcgi_hide_header X-Powered-By;
          }

          # Cache long-lived assets
          location ~* \.(css|js|ico|gif|jpe?g|png|svg|webp|woff|woff2|ttf|eot|pdf)$ {
              expires 120d;
              log_not_found off;
              access_log off;
              add_header Expires "Thu, 31 Dec 2037 23:55:55 GMT";
              add_header Cache-Control "max-age=315360000, public, immutable";
          }

      }
    }