{{ if  .Values.extraConfigMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-extra-config-map
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
{{- if  and .Values.extraConfigMap.create .Values.extraConfigMap.data }}
{{- range $index, $content := .Values.extraConfigMap.data }}
  {{ $index }}: |-
{{ $content | indent 4 }}
{{- end }}
{{- end }}
{{- end }}