apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    {{- include "wordpress.installationLabels" . | nindent 4 }}
    {{- include "wordpress.componentLabels" . | nindent 4 }}